# Generated by Django 4.2.6 on 2024-01-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('idEstadoCivil_wt', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_wt', models.CharField(max_length=100)),
                ('edad_wt', models.CharField(max_length=100)),
                ('numeroHijos_wt', models.IntegerField()),
                ('tiempoEstado_wt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('idMedicamento_wt', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_wt', models.CharField(max_length=100)),
                ('descripcion_wt', models.CharField(max_length=100)),
                ('efectosSecundarios_wt', models.CharField(max_length=100)),
                ('precio_wt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais_wt', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_wt', models.CharField(max_length=50)),
                ('capital_wt', models.CharField(max_length=50)),
                ('poblacion_wt', models.IntegerField()),
                ('idioma_wt', models.CharField(max_length=50)),
                ('moneda_wt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('idRaza_wt', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_wt', models.CharField(max_length=50)),
                ('descripcion_wt', models.CharField(max_length=100)),
                ('origen_wt', models.CharField(max_length=50)),
                ('esperanzaVida_wt', models.CharField(max_length=50)),
                ('caracteristica_wt', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtencion',
            fields=[
                ('idTipoAtencion_wt', models.AutoField(primary_key=True, serialize=False)),
                ('costo_wt', models.IntegerField()),
                ('especialidades_wt', models.CharField(max_length=100)),
                ('disponibilidad_wt', models.CharField(max_length=100)),
                ('tiempoEspera_wt', models.CharField(max_length=100)),
            ],
        ),
    ]
