# Generated by Django 4.2.6 on 2024-01-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocivil',
            name='actividad_wt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
