# Generated by Django 4.2.6 on 2024-01-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0002_estadocivil_actividad_wt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocivil',
            name='edad_wt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='numeroHijos_wt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='tiempoEstado_wt',
            field=models.IntegerField(default=0),
        ),
    ]
