# Generated by Django 4.2.6 on 2024-01-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0003_alter_estadocivil_edad_wt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocivil',
            name='numeroHijos_wt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='tiempoEstado_wt',
            field=models.IntegerField(),
        ),
    ]
