# Generated by Django 4.2.6 on 2024-01-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0004_alter_estadocivil_numerohijos_wt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocivil',
            name='actividad_wt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='raza',
            name='esperanzaVida_wt',
            field=models.IntegerField(default=0),
        ),
    ]
