# Generated by Django 4.2.6 on 2024-01-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0005_alter_estadocivil_actividad_wt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoatencion',
            name='comentarios_wt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
