# Generated by Django 4.2.6 on 2024-01-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0006_tipoatencion_comentarios_wt'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='instrucciones_wt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoatencion',
            name='comentarios_wt',
            field=models.CharField(max_length=100),
        ),
    ]
