# Generated by Django 4.2.6 on 2024-01-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0007_medicamento_instrucciones_wt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('idAtencion_wt', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_wt', models.DateField()),
                ('descripcion_wt', models.CharField(max_length=100)),
                ('costo_wt', models.IntegerField()),
                ('observaciones_wt', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='instrucciones_wt',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idreceta_wt', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEmision_wt', models.DateField()),
                ('dosis_wt', models.CharField(max_length=100)),
                ('instrucciones_wt', models.CharField(max_length=100)),
                ('duracion_wt', models.CharField(max_length=100)),
                ('atencion_wt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.atencion')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('idPropietario_wt', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_wt', models.CharField(max_length=100)),
                ('apellido_wt', models.CharField(max_length=100)),
                ('direccion_wt', models.CharField(max_length=100)),
                ('telefono_wt', models.IntegerField()),
                ('correo_wt', models.CharField(max_length=100)),
                ('estadoCivil_wt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.estadocivil')),
                ('pais_wt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota_wt', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_wt', models.CharField(max_length=100)),
                ('especie_wt', models.CharField(max_length=100)),
                ('edad_wt', models.IntegerField()),
                ('peso_wt', models.IntegerField()),
                ('propietario_wt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.propietario')),
                ('raza_wt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.raza')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('idDetalle_wt', models.AutoField(primary_key=True, serialize=False)),
                ('precioUnitario_wt', models.IntegerField()),
                ('descuento_wt', models.IntegerField()),
                ('subtotal_wt', models.IntegerField()),
                ('medicamento_wt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.medicamento')),
                ('receta_wt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.receta')),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='mascota_wt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.mascota'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='tipoAtencion_wt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.tipoatencion'),
        ),
    ]
