# Generated by Django 4.2.6 on 2024-01-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0008_atencion_alter_medicamento_instrucciones_wt_receta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='idreceta_wt',
            new_name='idReceta_wt',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fotografia_wt',
            field=models.FileField(blank=True, null=True, upload_to='medicamentos'),
        ),
    ]
