# Generated by Django 4.2.6 on 2024-01-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0009_rename_idreceta_wt_receta_idreceta_wt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='mascota_wt',
            field=models.FileField(blank=True, null=True, upload_to='mascotas'),
        ),
        migrations.AddField(
            model_name='pais',
            name='bandera_wt',
            field=models.FileField(blank=True, null=True, upload_to='banderas'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='copiaCedula_wt',
            field=models.FileField(blank=True, null=True, upload_to='cedulas'),
        ),
    ]
