# Generated by Django 4.2.6 on 2024-01-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0010_mascota_mascota_wt_pais_bandera_wt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='mascota_wt',
            new_name='imgMascota_wt',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='fotografia_wt',
            new_name='imgMedicamento_wt',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='bandera_wt',
            new_name='imgBandera_wt',
        ),
        migrations.RenameField(
            model_name='propietario',
            old_name='copiaCedula_wt',
            new_name='imgCedula_wt',
        ),
    ]
