# Generated by Django 4.2.6 on 2024-01-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0011_rename_mascota_wt_mascota_imgmascota_wt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propietario',
            old_name='imgCedula_wt',
            new_name='pdfCedula_wt',
        ),
    ]
